name: Static Website Test CI

on:
    push:
        branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Test
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} --auth-mode key -d '$web' -s . --pattern [!sass/*]
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name ${{ secrets.AZURE_CDN_PROFILE_NAME }} --name ${{ secrets.AZURE_CDN_ENDPOINT }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}

    - name: Logout Azure
      run: |
            az logout
      if: always()

    - name: Send push notification
      id: pushnotifier
      uses: bluefirex/pushnotifier-send-action@v1.0.1
      with:
        api-token: ${{ secrets.PUSHNOTIFIER_API_TOKEN }}
        app-token: ${{ secrets.PUSHNOTIFIER_APP_TOKEN }}
        package: com.github.resume
        device-ids: ElNN
        notification: CI action for Resume application to Test completed!
        url: https://github.com/richard-uzik-accenture/Resume
